"""Create participant_registrations table (replaces removed hex revisions).

History note: two autogenerated revisions (e06e85fca492, 8159621d23e9) briefly
existed after 0002 but were deleted before 0004. e06e85 only renamed unique
constraints to unique indexes (functionally equivalent - fresh DBs keep the
original constraint names, no action needed) and 8159621d23e9 was an empty
stub. Any database stamped at 0003 upgrades straight to 0004.

Revision ID: 0004_participant_registrations
Revises: 0003_gallery_visibility
"""
from alembic import op
import sqlalchemy as sa

revision = "0004_participant_registrations"
down_revision = "0003_gallery_visibility"
branch_labels = None
depends_on = None

registrations = sa.Table(
    "participant_registrations",
    sa.MetaData(),
    sa.Column("event_id", sa.Text(), primary_key=True),
    sa.Column("user_id", sa.Text(), primary_key=True),
    sa.Column("full_name", sa.Text(), nullable=False),
    sa.Column("email", sa.Text(), nullable=False),
    sa.Column("phone", sa.Text(), nullable=False),
    sa.Column("age", sa.Integer(), nullable=False),
    sa.Column("degree", sa.Text(), nullable=False),
    sa.Column("year_of_study", sa.Text(), nullable=False),
    sa.Column("institution", sa.Text(), nullable=False),
    sa.Column("category", sa.Text(), nullable=False),
    sa.Column("tshirt_size", sa.Text(), nullable=True),
    sa.Column("dietary_restrictions", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True)),
    sa.Column("updated_at", sa.DateTime(timezone=True)),
    # Name-only stubs so FKs resolve to the real events/users tables
    # (stubs are never created - only `registrations` is).
    sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
)

sa.Table("events", registrations.metadata, sa.Column("id", sa.Text(), primary_key=True))
sa.Table("users", registrations.metadata, sa.Column("id", sa.Text(), primary_key=True))


def upgrade() -> None:
    # checkfirst: databases seeded while the hex revisions existed may
    # already have this table via metadata.create_all().
    registrations.create(bind=op.get_bind(), checkfirst=True)


def downgrade() -> None:
    op.drop_table("participant_registrations")
