"""create_participant_registrations

Revision ID: 8159621d23e9
Revises: e06e85fca492
Create Date: 2026-09-25 17:30:59.074764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8159621d23e9'
down_revision = 'e06e85fca492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
