"""Add participant registrations table

Revision ID: e06e85fca492
Revises: 0002_visibility
Create Date: 2026-09-25 16:57:11.665306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06e85fca492'
down_revision = '0002_visibility'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_slug_key', 'events', type_='unique')
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index('ix_projects_event_status', 'projects', ['event_id', 'status'], unique=False)
    op.drop_constraint('sessions_token_hash_key', 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.drop_constraint('team_invites_token_hash_key', 'team_invites', type_='unique')
    op.create_index(op.f('ix_team_invites_token_hash'), 'team_invites', ['token_hash'], unique=True)
    op.drop_constraint('users_email_norm_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email_norm'), 'users', ['email_norm'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_norm'), table_name='users')
    op.create_unique_constraint('users_email_norm_key', 'users', ['email_norm'])
    op.drop_index(op.f('ix_team_invites_token_hash'), table_name='team_invites')
    op.create_unique_constraint('team_invites_token_hash_key', 'team_invites', ['token_hash'])
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.create_unique_constraint('sessions_token_hash_key', 'sessions', ['token_hash'])
    op.drop_index('ix_projects_event_status', table_name='projects')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.create_unique_constraint('events_slug_key', 'events', ['slug'])
    # ### end Alembic commands ###
